# Generated by Django 5.0.1 on 2026-02-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('HOT', 'Hot (SSD)'), ('COLD', 'Cold (HDD)')], default='HOT', max_length=10)),
                ('mount_point', models.CharField(help_text='Absolute path to the mount point', max_length=255)),
                ('capacity_bytes', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(help_text='Path relative to the tier mount point', max_length=512)),
                ('size_bytes', models.BigIntegerField()),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='file_management.storagetier')),
            ],
            options={
                'unique_together': {('tier', 'relative_path')},
            },
        ),
    ]
