# Generated by Django 5.0.1 on 2026-02-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfile',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
