# Generated by Django 5.0.1 on 2026-02-09 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_managedfile_is_encrypted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managedfile',
            name='top_level_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
