# Generated by Django 5.0.1 on 2026-09-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0004_sharedlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedfile",
            name="encrypted_dek",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managedfile",
            name="encryption_iv",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managedfile",
            name="original_checksum",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
